# Generated by Django 4.2.17 on 2024-12-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_consultation', models.AutoField(primary_key=True, serialize=False)),
                ('date_consult', models.DateField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id_dpi', models.AutoField(primary_key=True, serialize=False)),
                ('antecedents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id_infirmier', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id_medicament', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date_prescription', models.DateField()),
                ('etat_ordonnance', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='gestiondpi.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ParametreBiologique',
            fields=[
                ('id_parametrebiologique', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('unite_mesure', models.CharField(max_length=20)),
                ('valeur_normale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id_soin', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('date_soin', models.DateField()),
                ('observation', models.TextField()),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='gestiondpi.dpi')),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='gestiondpi.infirmier')),
            ],
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('id_radiologue', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id_prescription', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='gestiondpi.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacienHospitalier',
            fields=[
                ('id_pharmacienHospitalier', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('NSS', models.CharField(max_length=20, unique=True)),
                ('codeQR', models.CharField(max_length=255, unique=True)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('mutuelle', models.CharField(max_length=100)),
                ('personne_a_contacter', models.CharField(max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParametreBioMesure',
            fields=[
                ('id_parametrebiomesure', models.AutoField(primary_key=True, serialize=False)),
                ('valeur_mesuree', models.CharField(max_length=100)),
                ('date_mesure', models.DateField()),
                ('parametre_biologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='gestiondpi.parametrebiologique')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id_medecin', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
        migrations.CreateModel(
            name='Laborantin',
            fields=[
                ('id_laborantin', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('biologique', 'Biologique'), ('radiologique', 'Radiologique')], max_length=20)),
                ('description', models.TextField()),
                ('date_prescription', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='gestiondpi.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='gestiondpi.dpi'),
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id_bilanradiologique', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='radiologies/')),
                ('compte_rendu', models.TextField()),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan_radiologique', to='gestiondpi.examen')),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id_bilanbiologique', models.AutoField(primary_key=True, serialize=False)),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan_biologique', to='gestiondpi.examen')),
                ('parametres', models.ManyToManyField(related_name='bilans_biologiques', to='gestiondpi.parametrebiologique')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.user')),
            ],
        ),
    ]
