# Generated by Django 5.1.4 on 2025-01-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='antecedents',
            field=models.TextField(blank=True, default='Default Value', null=True),
        ),
    ]
