# Generated by Django 4.2.17 on 2024-12-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='dpi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medcin', to='gestiondpi.medecin'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicament',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='gestiondpi.medicament'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestiondpi.patient'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='gestiondpi.consultation'),
        ),
    ]
