# Generated by Django 5.1.4 on 2024-12-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0002_remove_prescription_medicament_delete_medicament'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicament',
            field=models.CharField(default='Default Value', max_length=100),
        ),
    ]
