# Generated by Django 5.1.4 on 2025-01-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0002_alter_consultation_ordonnance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='antecedents',
        ),
    ]
