# Generated by Django 4.2.17 on 2024-12-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0002_dpi_dpi_prescription_medicament_alter_dpi_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bilanbiologiques', to='gestiondpi.laborantin'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bilanradiologiques', to='gestiondpi.radiologue'),
        ),
    ]
