# Generated by Django 5.1.4 on 2025-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0002_alter_resume_antecedents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
