# Generated by Django 4.2.17 on 2024-12-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0003_bilanbiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpi',
            old_name='dpi',
            new_name='medecin',
        ),
    ]
