# Generated by Django 5.1.3 on 2024-12-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0005_remove_consultation_resume_dpi_qr_code_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='codeQR',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='consultation',
        ),
        migrations.AddField(
            model_name='consultation',
            name='ordonnance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='gestiondpi.ordonnance'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='gestiondpi.prescription'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='gestiondpi.resume'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='antecedents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(default='default_qr', unique=True, upload_to='qrcodes/'),
        ),
    ]
