# Generated by Django 5.1.3 on 2024-12-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0006_remove_ordonnance_consultation_remove_patient_codeqr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='ordonnance',
        ),
    ]
