# Generated by Django 5.1.3 on 2024-12-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0008_remove_examen_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='examen',
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='bilan_biologique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='gestiondpi.bilanbiologique'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='bilan_radiologue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='gestiondpi.bilanradiologique'),
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
    ]
