# Generated by Django 5.1.3 on 2024-12-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0009_remove_bilanradiologique_examen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilanbiologiques', to='gestiondpi.laborantin'),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilanradiologiques', to='gestiondpi.radiologue'),
        ),
    ]
