# Generated by Django 5.1.3 on 2024-12-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0011_alter_bilanbiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.AddField(
            model_name='consultation',
            name='ordonnance',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='gestiondpi.ordonnance'),
        ),
    ]
