# Generated by Django 5.1.3 on 2024-12-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0012_remove_consultation_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ordonnance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='gestiondpi.ordonnance'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='gestiondpi.resume'),
        ),
    ]
