# Generated by Django 5.1.3 on 2024-12-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0013_alter_consultation_ordonnance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ordonnance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Consultation', to='gestiondpi.ordonnance'),
        ),
    ]
