# Generated by Django 5.1.4 on 2024-12-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0015_remove_parametrebiomesure_parametre_biologique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='image',
        ),
        migrations.CreateModel(
            name='RadiologyImage',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='radiologies/')),
                ('bilan_radiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestiondpi.bilanradiologique')),
            ],
        ),
    ]
