# Generated by Django 5.1.4 on 2024-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0016_remove_bilanradiologique_image_radiologyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(unique=True, upload_to='qrcodes/'),
        ),
    ]
